config/routes.rb
Rails.application.routes.draw do

  resources :ratings
  resources :favourites
  resources :entrada_usuarios
  resources :event_tags
  resources :tags
  resources :eventos
  resources :followers
  post '/follower', to:'followers#create'
  get 'evento_comp/:id_creator', to:'eventos#comp'
  get 'evento', to:'eventos#index'
  put 'evento/:id', to: 'eventos#update'
  put 'report/:id', to: 'eventos#report'
  get 'evento/:id', to: 'eventos#show'
  get 'eventotag/:id', to: 'event_tags#show_tags'
  delete 'evento/:id', to: 'eventos#destroy'
  post 'crearevento', to:'eventos#create'
  delete '/event_tags', to: 'event_tags#destroy'
  delete '/follower', to: 'followers#destroy'
  get '/aviscas', to:'users#avis_cas'
  get 'liked/:user_id', to: 'favourites#liked'
  get 'followed_events', to: 'followers#followed_events'
  get 'report/:id', to:  'eventos#reported'

  resources :password_resets

  post '/password_resets/:id', to: 'password_resets#update'
  get '/editp/:id', to: 'password_resets#edit'
  get '/edit/', to: 'users#edit'


  get 'entrada_usuarios/:user_id', to:'entrada_usuarios#show'
  get 'entrada_usuarios', to:'entrada_usuarios#index'
  post 'entrada_usuarios', to:'entrada_usuarios#create'
  delete 'entrada_usuarios', to:'entrada_usuarios#destroy'
  get 'part_evento/:evento_id', to: 'entrada_usuarios#show_tickets_event'
  get 'participa', to:'entrada_usuarios#participa'
  put 'participa', to: 'entrada_usuarios#ha_participat'
  get 'es_participant', to:'entrada_usuarios#es_participant'

  post 'favourites', to: 'favourites#create'
  delete 'favourites', to: 'favourites#destroy'
  get 'like_event', to:'favourites#show'
  get 'follow_company', to: 'followers#followed'
  get 'ratings_company', to:'ratings#ratings_company'
  get 'numvaloracions', to:'ratings#numvaloracions'
  get 'rating_user_evento', to: 'ratings#rating_user_evento'
  resources :users
  get 'user', to: 'users#show'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  delete 'profile_pic', to: 'users#delete_profile_pic'
  get 'es_confirmat', to: 'entrada_usuarios#es_confirmat'
  
  get '/', to: 'application#index'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset 
    if user
    render json: {}, status: :ok
    end
  end
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  def update
    @message1=""
    @message2=""
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_send_at < 2.hours.ago
       redirect_to "https://eventic-api.herokuapp.com/edit" + "/" + @user.password_reset_token, :alert => "Password reset has expired."
    elsif @user.update(user_params)
      @user.save
      @message2=""
      @message1 = "Your password has been changed successfully"
      render :edit
    else
      @message1=""
      @message2 = "Your password change has failed"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :id, :password_confirmation, :password_reset_token)
  end

end

app/views/password_resets/edit.html.erb
<style>
  body{
      font-family: Arial, Helvetica, sans-serif;
      font-size: 13px;
    }
    .info, .success, .warning, .error, .validation {
      border: 1px solid;
      margin: 10px 0px;
      padding: 15px 10px 15px 50px;
      background-repeat: no-repeat;
      background-position: 10px center;
    }
    .info {
      color: #00529B;
      background-color: #BDE5F8;
      background-image: url('https://i.imgur.com/ilgqWuX.png');
    }
    .success {
      color: #4F8A10;
      background-color: #DFF2BF;
      background-image: url('https://i.imgur.com/Q9BGTuy.png');
    }
    .warning {
      color: #9F6000;
      background-color: #FEEFB3;
      background-image: url('https://i.imgur.com/Z8q7ww7.png');
    }
    .error{
      color: #D8000C;
      background-color: #FFBABA;
      background-image: url('https://i.imgur.com/GnyDvKN.png');
    }
    .validation{
      color: #D63301;
      background-color: #FFCCBA;
      background-image: url('https://i.imgur.com/GnyDvKN.png');
    }
</style>


<% if !@message1.blank? %>
 <div class="success"><%=@message1%></div>
 <%end%>
 <% if !@message2.blank? %>
 <div class="error"><%=@message2%></div>
 <%end%>


<center>
  <table border="0" width="100%" bgcolor="white">
    <th></th>
    <tbody>
      <tr>
        <td bgcolor = "steelblue"  class="tda">
           <table style="padding:15px" border="0">
            <th></th>
            <tbody >
              <tr>
                 <td style="width:18px; padding-right:4px"  class="tda">              
                  </td>
                  <td style = "line-height:12pt; height:10px;"  class="tda">
                    <span class="pagetop">                    
                    </span>
                  </td>                
              </tr>
           </tbody>   
          </table>
        </td>
      </tr>
    </tbody>
  </table>
  <h1><img width="30%" src="/Eventic.png" alt="Image not found" /></h1>
  <%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Update Password" %></div>
  <% end %>
</center>